# Generated by Django 3.2.2 on 2021-05-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_imageevent_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='poster_event',
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='imageevent',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
