# Generated by Django 3.2.2 on 2021-05-10 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210509_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicplace',
            name='poster',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ImagePublicPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True, null=True)),
                ('public_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_public_place', to='catalog.publicplace')),
            ],
        ),
    ]
