# Generated by Django 3.2 on 2021-06-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_eventsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsession',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_event', to='catalog.event'),
        ),
    ]
