# Generated by Django 3.2.2 on 2021-05-10 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210510_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
