# Generated by Django 2.2.6 on 2019-10-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_cafe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category'),
        ),
    ]
