# Generated by Django 3.2 on 2021-07-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210625_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageevent',
            name='youtubeId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
