# Generated by Django 3.2.2 on 2021-05-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_event_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['rating']},
        ),
    ]
