# Generated by Django 2.2.6 on 2019-11-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20191107_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='cousine',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.City'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.CharField(max_length=49),
        ),
        migrations.CreateModel(
            name='ItemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=49)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Country')),
            ],
        ),
    ]
