# Generated by Django 2.2.6 on 2019-11-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20191109_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='address_lan',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='address_lng',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='address_number',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='address_street',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone_home',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone_home_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone_kyivstar',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone_lifecell',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone_vodephone',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='social_facebook',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='social_instagram',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='social_www',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
