# Generated by Django 2.2.6 on 2019-11-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20191111_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='break_hour_in_weekend_from',
            field=models.TimeField(null=True, verbose_name='Break_from_in_weekend'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='break_hour_in_weekend_to',
            field=models.TimeField(null=True, verbose_name='Break_to_in_weekend'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='break_hour_in_weekend_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='break_hour_in_workdays_from',
            field=models.TimeField(null=True, verbose_name='Break_from_in_workdays'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='break_hour_in_workdays_to',
            field=models.TimeField(null=True, verbose_name='Break_to_in_workdays'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='break_hour_in_workdays_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone_kyivstar_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone_lifecell_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone_vodaphone_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='social_email',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='social_email_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='social_facebool_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='social_instagram_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='work_every_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='work_every_day_break_from',
            field=models.TimeField(null=True, verbose_name='Break_from'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='work_every_day_break_to',
            field=models.TimeField(null=True, verbose_name='Break_to'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='work_every_day_from',
            field=models.TimeField(null=True, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='work_every_day_to',
            field=models.TimeField(null=True, verbose_name='To'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='work_hour_in_weekday_from',
            field=models.TimeField(null=True, verbose_name='From_in_weekend'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='work_hour_in_weekday_to',
            field=models.TimeField(null=True, verbose_name='To_in_weekend'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='work_hour_in_workdays_from',
            field=models.TimeField(null=True, verbose_name='From_in_workdays'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='work_hour_in_workdays_to',
            field=models.TimeField(null=True, verbose_name='To_in_workdays'),
        ),
    ]
