# Generated by Django 2.2.6 on 2019-11-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20191111_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='tags',
            field=models.TextField(default=2, max_length=150, verbose_name='TAGS'),
            preserve_default=False,
        ),
    ]
