# Generated by Django 2.2.6 on 2019-11-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20191128_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='name',
            new_name='name_company',
        ),
        migrations.AddField(
            model_name='cafe',
            name='schedule',
            field=models.TextField(default=1, max_length=300, verbose_name='Schedule'),
            preserve_default=False,
        ),
    ]
