# Generated by Django 2.2.6 on 2019-11-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20191128_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='schedule',
        ),
    ]
