# Generated by Django 2.2.6 on 2019-12-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_cafe_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='address_street',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='address_lan',
            new_name='address_pattern_lat',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='address_lng',
            new_name='address_pattern_lng',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='address_number',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='phone_home_use',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='phone_kyivstar_use',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='phone_lifecell_use',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='phone_vodaphone_use',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='social_email_use',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='social_facebool_use',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='social_instagram_use',
        ),
    ]
