# Generated by Django 2.2.6 on 2019-12-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20191202_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='tags',
        ),
    ]
