# Generated by Django 2.2.6 on 2019-12-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_remove_cafe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='schedule',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='social_email',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='social_facebook',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='social_instagram',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='social_www',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
