# Generated by Django 3.0.2 on 2020-01-31 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20191202_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidaySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_time_from', models.TimeField()),
                ('work_time_to', models.TimeField()),
                ('break_time_from', models.TimeField(blank=True, null=True)),
                ('break_time_to', models.TimeField(blank=True, null=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=9)),
                ('work_time_from', models.TimeField()),
                ('work_time_to', models.TimeField()),
                ('break_time_from', models.TimeField(blank=True, null=True)),
                ('break_time_to', models.TimeField(blank=True, null=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Cafe')),
            ],
            options={
                'unique_together': {('cafe', 'day')},
            },
        ),
    ]
