# Generated by Django 3.0.2 on 2020-01-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20200131_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.City'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Country'),
        ),
    ]
